### ISSUE TITLE
CMD windows popping open then closing when running Card Farming

### ISSUE THREAD

**Issue by rhize84** [probablyraging/steam-game-idler#12]
### Describe the issue

When Card Farming running, SGI will open and close windows command instances. 

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Thanks for the report.

This is fixed in `v1.3.4` with abe57a2ad46d0942baa88f018efd565cbc748bf0

SGI should automatically update the next time you run it.
