### ISSUE TITLE
Durations

### ISSUE THREAD

**Issue by RandomIndividual1982** [probablyraging/steam-game-idler#16]
### Describe the feature

I wondered if different time durations for achievements for different games is possible?

### Which branch of SGI?

Base

### Is your feature request related to an issue?

No

**Comment by probablyraging** [comment]
Hi mate, I'm not sure I fully understand.

Do you mean is it possible to change how frequently achievements unlock when running the `achievement unlocker` feature? If so, yes. You can change the `unlock interval` setting in `settings > achievement unlocker`.

If you mean being able to set and store an `unlock interval` on a per game basis, so you don't need to manually change the setting each time, for different games, no there is no option for that, I don't think adding such a feature would be all that beneficial as changing this setting takes like a couple of seconds at most.

Unless I am mistaken as to what you mean.

**Comment by MojoDex** [comment]
I meant the second one, but on a running multiple games basis. For example;
Civ 5 running with it set to unlovk an achivement every 10-12 hours and
Sifu also running and set to unlock an achievment every 1-2 hours. If it's
not in the pipeline that's ok, but thought I'd ask. Thanks for the program,
regardless. It's working a treat!

**Comment by Meszaros91** [comment]
I would like to add maybe not related to this post 

But a feature to select times where the program farms the achievents in achivement farms list  so example you sleep between 2am and 10 am so it wont farm  between those hours 

And the another feature to select how many hours the app should farm a game and then swutch games at the end of that specified time so you can scramble the games and have more realistic unlocks on games played frequently rather than only 1 game unlocked at a time 
Example #1  : i want to farm game 1 for (x to y ) random amount of hours selected in menu like achivement unlocker  and then it switches to game 2 for random number between (x and y) and so on moving randomly in your achivement unlocker list 

This would create more random dates and real life simulation 


Sorry if i stepped on your thread 

And also love your work doing good for real love to tlsee the progress u are making


Ex #2

**Comment by probablyraging** [comment]
> I meant the second one, but on a running multiple games basis. For example; Civ 5 running with it set to unlovk an achivement every 10-12 hours and Sifu also running and set to unlock an achievment every 1-2 hours. If it's not in the pipeline that's ok, but thought I'd ask. Thanks for the program, regardless. It's working a treat!

I understand now, thanks for clarifying.

Yeah I can understand where a need for different intervals on a per game basis might come in to play in that scenario.

I won't confirm if this will be added as a feature right now. I will keep this issue open to feedback from others and make a decision based off that.

In the mean time, what you could do is the following;
- Run an instance of SGI
- Add only Civ5 to your `achievement unlocker list`
- Set your `unlock interval` to the `10-12` hours
- Run a second instance of SGI
- Repeat the steps making sure only Sifu is added to the list, with different `unlock interval` settings

Though this is not the prettiest solution, it should would as expected.

**Comment by probablyraging** [comment]
> I would like to add maybe not related to this post
> 
> But a feature to select times where the program farms the achievents in achivement farms list so example you sleep between 2am and 10 am so it wont farm between those hours
> 
> And the another feature to select how many hours the app should farm a game and then swutch games at the end of that specified time so you can scramble the games and have more realistic unlocks on games played frequently rather than only 1 game unlocked at a time Example #1 : i want to farm game 1 for (x to y ) random amount of hours selected in menu like achivement unlocker and then it switches to game 2 for random number between (x and y) and so on moving randomly in your achivement unlocker list So if you have 10 games in achivement list maybe app will unlock game 2 then gane 8 then game 5 and so on untill the games is done achieving 100% and get dropped from the list
> 
> This would create more random dates and real life simulation
> 
> Sorry if i stepped on your thread
> 
> And also love your work doing good for real love to tlsee the progress u are making
> 
> Ex #2

Solid ideas, thanks for suggesting them. I've created a new issue for these (https://github.com/probablyraging/steam-game-idler/issues/17) and I'll look into them when I get the chance!

**Comment by probablyraging** [comment]
I've decided to not add this as a feature as I feel like an easy solution is to just run multiple instances of SGI with different settings as mentioned above.

Thanks again for the suggestion though. If you have any more, or run in to any other issues, let me know.
