### ISSUE TITLE
Scheduled achievement unlocker

### ISSUE THREAD

**Issue by probablyraging** [probablyraging/steam-game-idler#17]
I would like to add maybe not related to this post 

But a feature to select times where the program farms the achievents in achivement farms list  so example you sleep between 2am and 10 am so it wont farm  between those hours 

And the another feature to select how many hours the app should farm a game and then swutch games at the end of that specified time so you can scramble the games and have more realistic unlocks on games played frequently rather than only 1 game unlocked at a time 
Example #1  : i want to farm game 1 for (x to y ) random amount of hours selected in menu like achivement unlocker  and then it switches to game 2 for random number between (x and y) and so on moving randomly in your achivement unlocker list 
 So if you have 10 games in achivement list maybe app will unlock game 2 then gane 8 then game 5 and so on untill the games is done achieving 100% and get dropped from the list 

This would create more random dates and real life simulation 

Sorry if i stepped on your thread 

And also love your work doing good for real love to tlsee the progress u are making

Ex #2

_Originally posted by @Meszaros91 in https://github.com/probablyraging/steam-game-idler/issues/16#issuecomment-2323025636_

**Comment by probablyraging** [comment]
> But a feature to select times where the program farms the achievents in achivement farms list so example you sleep between 2am and 10 am so it wont farm between those hours

@Meszaros91

The scheduler/sleep feature is added in `v1.3.4` with https://github.com/probablyraging/steam-game-idler/commit/dab7f1ef5bc73c0943498b05a7993d9811af7a9f

I'll look further in to the other feature you mentioned within the next couple of days. It's a bit more complex, and I'm still weighing up if it is worth implementing or not.

SGI should automatically update when you launch it next.

**Comment by Meszaros91** [comment]
Fast response and implementation 

I will be testing it tonight  and come back to you with an update in the morning 

the other feature would be a bit like this 

(Detect game ID position in the list (achievement unlocker list)  then set a random timer in the menu the user can set times played before the game switch 

automate the process of closing the game being farmed (AchVmt) after a random amount time countdown and then select a random game and start farming achievement unlock on that game until the list has no more games ( also the random times between achievement If the last achivement is unlocked under X amount of time it will wait until X amount of time is elapsed to unlock another achievement on the new game selected ) 

hope that was clear let me know if you have trouble understanding 
just a suggestion i understand I can be hard to implement but would be cool xD and above anything else out there !!! 

take your time 
have a great night/day

**Comment by probablyraging** [comment]
Thanks for clarifying, I understand what you mean and it's definitely an interesting idea. While it wouldn't be too hard to implement, I'm more just considering whether it fits SGI's use case or not. Currently, users can achieve similar results manually with minimal effort, which might actually contribute to a more "human-like" result in the long run.

One thing I want to make sure of is that SGI is easy to use right out of the box, with as little config needed as possible. I don't really want to bloat it with features that address edge cases. The goal is to keep a balance between useful automation and user control.

That's not saying I won't implement that second suggestion, I just want to think on it for a couple of days. so if I can see the benefit of adding certain features I definitely will. The `schedule` feature is a great example of this. I'm surprised I didn't think of it myself, because it definitely has a massive benefit in terms of keeping achievement unlocking looking as human-like as possible, because no normal human is playing a game 24/7 consistently unlocking achievements. So adding a feature to allow SGI to "sleep" and resume again automatically makes complete sense.

Sorry for the lengthy response, just want to make sure you understand I'm not negging your suggestion and explain my reason for thinking on it a little more 👍🏼

**Comment by Meszaros91** [comment]
All good and yes no worries its already great and you a right its easy to go do it manually ect  i agree i am just lazy hahhaha but this timeout is dope gonne update you on it and if there is any issues

**Comment by Meszaros91** [comment]
As of now it works great this morning i woke up and it was waiting standby 
Then 15 min late lr on sceduke restared to count time  i was not there to see it for myself but it worked i will leave it idle for couples days and will update you 


Also 1 quick question i am not sure but i tend to close all apps and restart them sometimes wheb i see my steam dosent detect all the games open anymore after few hours or overnight i tend to restart everything to make steam detect im in game for those games 

Always under 32 games running consecutively 
Also had a request timeout for my steam last week havebt checked bu5 when i get back hone ill check this qnd let you know if it still happens your developement is goibg fast so maybe it wont anymore 

I am just putting it out there for ya 

Speak later and thanks for your good work
Im on phone and txt badly sorry for any errors i will edit infront of my pc

**Comment by probablyraging** [comment]
Sorry, been a busy couple of days and totally forgot to reply to this.

> As of now it works great

Good to hear!

> Also 1 quick question i am not sure but i tend to close all apps and restart them sometimes wheb i see my steam dosent detect all the games open anymore after few hours or overnight i tend to restart everything to make steam detect im in game for those games

Steam should always detect the game is running, assuming you have a stable internet connection, it isn't dropping out from time to time, and as long as the idle window stays open. If you computer goes into hibernation/sleep, this might also affect it, but I've not tested that. But yeah, I've left multiple idle windows open for multiple days on end without an issue.

How exactly are you checking if Steam still detects the game idling? All you need to check is if the total playtime is still increasing, keep in mind that the playtime doesn't update immediate, there is like a 10+ minute delay, maybe longer depending on how many hours you already have in the game, but I can guarentee that if the idle window/process is open and running, and you've got a stable connection, your game is correctly being idled and Steam will detect it, and it will do so indefinitely.

> Also had a request timeout for my steam

This sounds like a Steam issue, either Steam was having issues, or you hit a rate limit by doing something within Steam desktop/website too frequently. Something like updating your avatar, posting reviews, or commenting on profiles.

I don't see this being an issue with SGI though, as SGI uses the Steamworks SDK, and to my knowledge it doesn't have any rate limits, unlike the web API.

> And the another feature to select how many hours the app should farm

Going back to this feature request. I think I have decided I won't be implementing it, as it is very easy to accomplish manually. So I am going to close this as completed now.

Thanks again. Feel free to open another issue if you run into any other problems, or have any other questions.
