### ISSUE TITLE
Welcome Loading loop

### ISSUE THREAD

**Issue by Kronos1107** [probablyraging/steam-game-idler#18]
### Describe the issue

Just downloaded the latest edition of the app. I'm just stuck on this loop and I have no idea what to do. Some rare moments it goes through but the games list doesn't load in.

https://github.com/user-attachments/assets/11898e47-0a4f-4f03-875b-ed363ba1a135

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
I've just released `v1.5.0`, would you mind updating and giving that version a try?

SGI should automatically update when you launch it next, or you can download `v1.5.0` from the releases page.

If that doesn't solve the issue, can you go to `C:\Users\<user_account>\AppData\Roaming\steam-game-idler` and check if you have a `log.txt` file. If so, can you upload it here for me to look at.

Cheers

**Comment by Kronos1107** [comment]
Hi.

I updated it to the latest version. 1.5.6, the same issue persists.

Here I'll attach the log file for you to look through.

[log.txt](https://github.com/user-attachments/files/16854574/log.txt)

**Comment by probablyraging** [comment]
Thanks for providing that.

It appears your connection is being forcibly closed for whatever reason, Could be firewall, antivirus, bad internet connection.

When you first launched SGI, you might have seen a screen asking you to allow outgoing connections, and not accepted it, try the following and see if it works;

1. Open the Windows Control Panel
2. Go to System and Security > Windows Defender Firewall
3. Click on "Allow an app or feature through Windows Defender Firewall"
4. Click "Change settings" and then "Add another app..." and then "Browse"
5. Navigate to the install directory of the app you want to add, select it, and click "Open"
6. Check the boxes for "Private" and/or "Public" networks as needed
7. Click "OK" to save the changes

By default, SGI is installed to `C:/Program Files/Steam Game Idler/` - you want to add the `Steam Game Idler.exe` to you firewall's allow list.

But unfortunately this is not an issue with SGI, but rather your network config, so unfortunately I can't really help much more.

**Comment by Kronos1107** [comment]
Hello,

So I finally got it working again. Just need a full system format lmao.

I assume there was some OS error/corruption somewhere that kept blocking the app, in fact it started effecting other Apps like Discord & GOG. So I tried all your advice and more, nothing worked so I decided to go with the Nuclear option and formatted the whole system.

**Comment by probablyraging** [comment]
Glad you got it working in the end mate
