### ISSUE TITLE
Feature Request: Linux Support

### ISSUE THREAD

**Issue by evman** [probablyraging/steam-game-idler#2]
Thank you for taking the time to make this. Would love to see Linux (eg. Debian/Ubuntu) support for this product so I can idle on my server instead of my home PC.

Thank you!

**Comment by ProbablyRaging** [comment]
Thanks mate, not a problem at all, I'm glad you like it!

I'm not super familiar with developing specifically for the linux environment but I'd be happy to take a crack at it. Though I'm almost positive there would be some repos that already exists that do what SGI does for linux.

Either way I'll look in to it over the next couple of days, see what I can come up with, and keep you updated.

**Comment by evman** [comment]
Thank you for the reply! Up to you bro! Would be really cool to see. I think going the Web UI approach would be sick where you could just access the panel via https://IP/ReverseProxyHere, would allow it to be cross platform as well.

If you dont want to go linux, any input would be appreciated on what repo to go with, thanks mate!

**Comment by ProbablyRaging** [comment]
I've actually already started working on a CLI version in nodejs using [steam-user](https://www.npmjs.com/package/steam-user).

So far it does exactly what the `lite` version of SGI does *(without the UI obviously)*. Basically taking a single, or multiple comma seperated game IDs and idles them for the user. It does require the user to sign in to the steam-user client with their username and password however. 

It's a popular enough repo that I feel confident in it being safe to use, and a quick audit of the codebase looks good. It also adopts the 2FA stream from the Steam auth process, requiring users with 2FA enabled to have access to their Steam Guard, for an extra layer of security.

It should be possible to build a web UI on top of what I already have, so I will look in to that once I get the basics done.

**Comment by ProbablyRaging** [comment]
Just pushed a cli + web ui version of SGI to https://github.com/ProbablyRaging/steam-game-idler/tree/cli-webui

Feel free to give it a try and let me know what you think, and let me know if you have any issues 👍

**Comment by evman** [comment]
Thanks so much man, I will give it a shot most likely this weekend when I have some time, btw I sent you a f/r on discord from evan_ -- much appreciated for your time on this!

**Comment by ProbablyRaging** [comment]
No worries at all, happy to do it. Not sure I got your FR, unless you're `ganjadood`?
