### ISSUE TITLE
Error: startAchievementUnlocker

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#20]
### Describe the issue

Sep 03 10:27:19.460 + [Error] in (startAchievementUnlocker) TypeError: Cannot destructure property 'achievements' of '(intermediate value)' as it is undefined.
Sep 03 10:27:19.459 + [Error] in (fetchAchievements) TypeError: Cannot read properties of undefined (reading 'toString')

![image](https://github.com/user-attachments/assets/514a95c6-191c-4178-a1b8-864d31dd1b2b)

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by Jesewe** [comment]
> ### Describe the issue
> Sep 03 10:27:19.460 + [Error] in (startAchievementUnlocker) TypeError: Cannot destructure property 'achievements' of '(intermediate value)' as it is undefined. Sep 03 10:27:19.459 + [Error] in (fetchAchievements) TypeError: Cannot read properties of undefined (reading 'toString')
> 
> ![image](https://private-user-images.githubusercontent.com/81848878/363852479-514a95c6-191c-4178-a1b8-864d31dd1b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDIyMjQsIm5iZiI6MTcyNTM0MTkyNCwicGF0aCI6Ii84MTg0ODg3OC8zNjM4NTI0NzktNTE0YTk1YzYtMTkxYy00MTc4LWExYjgtODY0ZDMxZGQxYjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1Mzg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YzMxODYyMzE4ZTE1NzYwZjJkNjRiYjgyNjRlNzQ3MTA4OTBlZGU1NzZhYzM0N2QyMDdjNjJiYTdjODRiMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lCwklMcqFuggmL4DW3PInqzlazI1qHE_E18DKNXCWV4)
> 
> ### Which branch of SGI?
> Base
> 
> ### What version of SGI are you using?
> Latest version

Also Infinite Loop - Achievement Unlocker
![image](https://github.com/user-attachments/assets/716e8479-00b8-431a-a473-f405153c1ccd)

**Comment by probablyraging** [comment]
Thank for reporting this issue mate.

This is fixed in `v1.5.3` with https://github.com/probablyraging/steam-game-idler/commit/25cb6591918fb74d8d3b639fb8e04eb094b3b3ed

This issue was occurring because one or more games in your `achievement unlocker` list have no achievements, and SGI wasn't handling this properly. Now, if there is a game in your list with no achievements, you will see a `finished` screen, and the game will be removed from the list`

**Comment by probablyraging** [comment]
Just a note, more for myself than anything. If you have the `skip hidden achievements` option enabled, and you add a game that has all hidden achievements to the `achievement unlocker` list, it will treat the game as if it has `0` achievements
