### ISSUE TITLE
Bug: Achievement Unlocker

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#21]
### Describe the issue

The program shows each game has 0 achievements and terminates.

![image](https://github.com/user-attachments/assets/4564cb0d-2293-45e3-b277-f2f2fc649eec)

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Ah yep, sorry.

Fixed in `v.1.5.4` with https://github.com/probablyraging/steam-game-idler/commit/81af9af5a8fccf7be2fdda95339985f0cbc70f92

Thanks again! Let me know if you run into any other issues
