### ISSUE TITLE
Unable to access the web ui

### ISSUE THREAD

**Issue by iminamoto** [probablyraging/steam-game-idler#22]
### Describe the issue

i'm running the app on a vps and i opened port 3000 still unable to access the webui

### Which branch of SGI?

CLI + WebUI

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Might be worth changing the port to something other than `3000` as your VPS might claim that port for something else. If you're not savvy with configuring a network interface, it might be worth just trying a different port in a range that isn't commonly used such as `49152-65535`

**Comment by iminamoto** [comment]
didnt work i tried port 49152 ! still same issue

**Comment by probablyraging** [comment]
> didnt work i tried port 49152 ! still same issue

This isn't really an issue with SGI though, it's likely an issue with your VPS's network config mate, and would be nearly impossible to debug without more information;
- What OS is your VPS running
- Are you trying to access the webui locally on the same machine, or remotely from a different machine?
- Have you configured your VPS network, firewall, etc, and if so how?
- Did you get any error messages in the terminal when installing depsendencies or when building the cli?
