### ISSUE TITLE
Idea: Background Achievement Unlock

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#23]
### Describe the feature

Is it possible to make the game **(SteamUtility.exe)** run as a background task when `unlocking achievements`? Suppose such a feature could be `enabled`/`disabled` in the settings. **Thanks in advance.**

### Which branch of SGI?

Base

### Is your feature request related to an issue?

No

**Comment by probablyraging** [comment]
This feature is added in `v1.5.7` with https://github.com/probablyraging/steam-game-idler/commit/e47d6d17b48bfbf33e464dfa4652c41e81d32f78

- Added a `stealth idle windows` to `settings > general`
  - Allows users to idle games with no external idle window appearing on the desktop
  - When active, if manually idling one or more games, you will have to manually end the idler process `(SteamUtility.exe)` for each game from Windows task manager. This task is done automatically during `card farming` and `achievement unlocker` tasks
  - If you manually idle multiple games at once, you likely won't know which process is for which game, as the process itself isn't uniquely named like the idler window is
  
Thanks again for the suggestion!
