### ISSUE TITLE
Bug: game does not close after unlocking all achievements

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#24]
### Describe the issue

After completing unlocking achievements in the game, idle continues to work...
![image](https://github.com/user-attachments/assets/be813ee5-3faf-4a60-9352-9481fcc9bc65)
Steam Library:
![image](https://github.com/user-attachments/assets/20fd0491-8422-40f2-b4e3-93223f165991)

### Which branch of SGI?

Base

### What version of SGI are you using?

Older version

**Comment by probablyraging** [comment]
Interesting, thanks for reporting. I will take a look at this shortly

**Comment by probablyraging** [comment]
This is fixed in `v1.5.7` with https://github.com/probablyraging/steam-game-idler/commit/e47d6d17b48bfbf33e464dfa4652c41e81d32f78

If the issue persists, feel free to reply to this issue
