### ISSUE TITLE
bug? Anti-away status

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#28]
### Describe the issue

How does the `Anti-away status` function work? Is it supposed to hide `idling` in games? If this is the case, then this function - **does not work.**

![image](https://github.com/user-attachments/assets/7cd63c59-e2ea-4a3a-8e47-a23d8421008f)
![image](https://github.com/user-attachments/assets/c76b5122-3eeb-494e-b096-57f956d34847)

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [X] I have included screenshots/videos
- [ ] I have included a log.txt file
- [ ] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Thanks for reaching out.

The `anti-idle status` feature works by preventing Steam from setting your profile status to `away`, while SGI is running.

By default, if you don't interact with your computer for 5 minutes, you will appear as `away` to your Steam friends, which I thought didn't seem realistic if a person was supposed to be playing a game and earning achievements, yet their status has been set to away the entire time.

I assume most people run SGI while not at their computer, so I thought this would be a good way to prevent that from happening, by forcing the user's status to always be `online`.

![image](https://github.com/user-attachments/assets/70c8035d-a464-4d48-ba37-81203db70f83)

There isn't really a way to idle a game without it showing that you're playing the game on Steam, if that is what you thought it was supposed to do. You would be better off just setting your status as `invisible` or `offline` at that point.

Hope that clears it up. Let me know if I can help you with anything else.
