### ISSUE TITLE
Unable to login using Web-UI when 2FA is enabled

### ISSUE THREAD

**Issue by Slaurits** [probablyraging/steam-game-idler#3]
### Describe the issue

When you attempt to login to webui, it wont ask for 2fa
In the attached image, I've put my login name and password, and pressed accept on my phone using steam guard.
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/e48d5ae5-0ff6-4b25-8468-653616ac06b9)

The CLI version works perfectly though

### Which branch of SGI?

CLI + WebUI

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Thanks for reporting this mate!

I've have just pushed an update that should now allow logging in to and idling games on Steam Guard protected accounts via the web ui abe2ae1.

Steam Guard protected accounts will now be required to provide a 5-digit code when logging in and beginning to idle games via the web ui. This means that each time you attempt to idle a game after your current 2FA session has expired, you will need to re-enter a new code in the command/terminal window, if you don't see the `started idling [game name]` message after entering your code you will need to stop and start idling your game(s) again, read more about this under the [Using Steam Guard](https://github.com/probablyraging/steam-game-idler/tree/cli-webui?tab=readme-ov-file#using-steam-guard) section.

Let me know if you have any further issues 🙂

**Comment by Slaurits** [comment]
I think you forgot to add the latest to show it works
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/6f549786-2474-4ea6-b591-4cc36793cb5f)
And when you press enter, and choose web-ui or arrow down, it just exits.
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/d25feb91-3033-45eb-929f-1ccfad827090)

**Comment by probablyraging** [comment]
Sorry, was a little rushed and forgot to properly update the version. Have also fixed the issue with it unexpectedly exiting after the notification update.

**Comment by Slaurits** [comment]
Cheers! I'll check it out now
