### ISSUE TITLE
"Steam is not running"

### ISSUE THREAD

**Issue by rdeserm** [probablyraging/steam-game-idler#30]
### Describe the issue

**This seems to only affect the games under the category "Favorited games"**

Always get the error "Steam is not running".

This is the error in the logs when trying to idle a game from my favorites:
[v1.5.19] [Error] in (startIdler) util: TypeError: Cannot read properties of undefined (reading 'toString')

If I sort by a different method like "Title Descending" I can idle the same game.  Also the search function no longer works for me as well.

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [ ] I have included screenshots/videos
- [ ] I have included a log.txt file
- [X] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Thanks for reporting mate.

This is likely related to #26 and can be fixed by doing the following
1. Go to `settings > general` and enable `Delete locally saved data on logout`
2. Log out of SGI
3. Add your games back to the `achievement unlocker` list and try running it again

Let me know if that works for you

**Comment by rdeserm** [comment]
That seemed to clear all my favorite games which is fine, but the "Search for a game" bar is no longer working for me.  I can activate the cursor but keyboard input not registering.

The games I added back to favorites is working though, thanks

**Comment by probablyraging** [comment]
Good to hear that's fixed it.

Would you be able to provide a screenshot of SGI while the search bar isn't working?

**Comment by rdeserm** [comment]
With the most recent update today, it's now working, thanks for the help!
