### ISSUE TITLE
SGI forces steam friends list visibility to Online

### ISSUE THREAD

**Issue by asofd** [probablyraging/steam-game-idler#33]
### Describe the issue

I always have my status on steam friends list set to Invisible but when I tried to idle some games using SGI it would force set my status to Online . Changing it manually back to Invisible is only temporary, SGI eventually forces me back into Online

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [ ] I have included screenshots/videos
- [ ] I have included a log.txt file
- [ ] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
You likely have the `anti-away status` option enabled in `settings > general`, disabling it will prevent this
