### ISSUE TITLE
Separate viewable Tab/List for Achievement or Idling.

### ISSUE THREAD

**Issue by Kronos1107** [probablyraging/steam-game-idler#34]
### Describe the feature

Hi, 

As the title says, simply put a separate tab/list where you add the games you want to achievement hunt or simply idle. Right now its a bit difficult to track all the games you've put up for Achievement Hunt.

A separate viewable section of such games would be very useful.

### Which branch of SGI?

Base

**Comment by probablyraging** [comment]
This already exists mate, you're able to view the games in the `achievement unlocker list` by seleting it from the sort drop down
![image](https://github.com/user-attachments/assets/323db8c9-b45d-4b60-844d-dcd29817068d)

**Comment by Kronos1107** [comment]
I need to get new glasses then lmao
