### ISSUE TITLE
SGI: Game statistics

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#36]
### Describe the feature

I'm getting tired of hitting the “Update” button.

![image](https://github.com/user-attachments/assets/ee045964-58c2-47dc-aac5-9fd44f78920e)

You can add a button in Statistics "Update all"

### Which branch of SGI?

Base

### Is your feature request related to an issue?

No

**Comment by probablyraging** [comment]
I'm away on vacation at the moment, but will definitely look in to this when I am back, though I feel like there was a reason why I didn't add this originally but I can't remember why, so no guarantees.

Cheers

**Comment by probablyraging** [comment]
If you would like to work on this feature request yourself, feel free to create PR and I will get to it when I can 👍

**Comment by zevnda** [comment]
Sorry it took me a minute to get around to adding this feature.

Added a `Save changes` button in `1.5.28`
