### ISSUE TITLE
SGI Bug

### ISSUE THREAD

**Issue by Jesewe** [probablyraging/steam-game-idler#37]
### Describe the issue

Often, after closing the program _(it should hide in the tray)_, it closes completely, crashes, and after opening the window size is minimized. Also, after switching to the lock screen **(WIN + l)**, the program simply stops working.

![screen](https://github.com/user-attachments/assets/6711bf8c-99ae-4014-b154-492043e8b829)

**Nothing much is written in the logs:**
[log.txt](https://github.com/user-attachments/files/17433286/log.txt)

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [X] I have included screenshots/videos
- [X] I have included a log.txt file
- [X] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
I'm not able to reproduce this error. Are you able to provide steps to reproduce it at all? What are you doing at the time this bug occurs (idling games, running achievement unlocker, card farming, etc)? As much information as you can provide will help.

When you say it crashes, how do you determine it has crashed? Do you get any Windows error messages, or something else? Can you provide screenshots of any relevant messages that appear on your screen at the time?

If you press **WIN + R** and in the dialog type **eventvwr.msc** and hit enter. In **Event Viewer** on the left side go to **Windows Logs > Applications**. Around the same time that you say SGI crashes, do you see any errors here?

Can you provide screenshots of all the SGI settings tabs?

What is your Windows version? **WIN + R** > type in **winver** > **Enter**

> and after opening the window size is minimized

To fix this, can you try a combination of the following hotkeys to see if they restore the window?
```
Minimize window:
Windows key + Down Arrow (press once)
Maximize window:
Windows key + Up Arrow
Restore/Minimize maximized window:
Windows key + Down Arrow
Snap window to left half of screen:
Windows key + Left Arrow
Snap window to right half of screen:
Windows key + Right Arrow
Snap window to a corner (quarter of the screen):
Windows key + Left/Right Arrow, then Up/Down Arrow
Minimize all windows:
Windows key + M
Restore all minimized windows:
Windows key + Shift + M
Toggle between maximized and previous size:
Windows key + Shift + Up Arrow
Move window between monitors:
Windows key + Shift + Left/Right Arrow
```

> Also, after switching to the lock screen (WIN + l), the program simply stops working.

Probably best to not lock the desktop when running SGI mate. What is the reason for doing so anyway?

I can't really say how the Steam client, Steamworks SDK, webview2, or any other SGI libraries are affected while the desktop is locked. As this doesn't really sound like an issue with SGI and is more likely an intentional Windows feature, I won't be looking in to this.

**Comment by Jesewe** [comment]
> When you say it crashes, how do you determine it has crashed? Do you get any Windows error messages, or something else? Can you provide screenshots of any relevant messages that appear on your screen at the time?

No error messages from Windows. For example, I run "Achievement Unlocker" and close the programm (so that it moves to the tray), but when the programme closes, it just exits. And when I reopen SGI, the window size changes to the very minimum (~200x100 pixels)

**Comment by Jesewe** [comment]
> Probably best to not lock the desktop when running SGI mate. What is the reason for doing so anyway?

I enabled the transition to the lock screen after 30 minutes of downtime. The computer runs very quietly, and it is convenient.

**Comment by Jesewe** [comment]
> Can you provide screenshots of all the SGI settings tabs?

![image](https://github.com/user-attachments/assets/1e0e101c-3b85-49c7-b3f3-af495e2156fb)

**Comment by Jesewe** [comment]
> If you press **WIN + R** and in the dialog type **eventvwr.msc** and hit enter. In **Event Viewer** on the left side go to **Windows Logs > Applications**. Around the same time that you say SGI crashes, do you see any errors here?

No errors or warnings, just information

**Comment by Jesewe** [comment]
> I'm not able to reproduce this error. Are you able to provide steps to reproduce it at all? What are you doing at the time this bug occurs (idling games, running achievement unlocker, card farming, etc)? As much information as you can provide will help.

In the moment, achievement unlocker, I just open YouTube/VSCode and start relaxing, well, or working.

**Comment by probablyraging** [comment]
> For example, I run "Achievement Unlocker" and close the programm (so that it moves to the tray), but when the programme closes, it just exits. And when I reopen SGI, the window size changes to the very minimum (~200x100 pixels)

I followed your steps to reproduce the issue with the **general** settings you provided, but I am still unable to reproduce the issue.

https://github.com/user-attachments/assets/be8baccc-fc70-4a6b-9ccc-76436ee23cea

Just to confirm, when following your steps, does the issue happen every time, or only sometimes?

Can you also provide a screenshot of **settings > achievement unlocker**?

> I enabled the transition to the lock screen after 30 minutes of downtime. The computer runs very quietly, and it is convenient.

I understand, but yeah as mentioned, Windows likely does stuff in the background to limit certain processes and Windows APIs when the desktop is locked (I assume), which could prevent SGI, Steam, Steamworks SDK or any other dependencies from functioning correctly. This is out of my control and my recommendation is to just not lock the desktop while using SGI.

> In the moment, achievement unlocker, I just open YouTube/VSCode and start relaxing, well, or working.

Are you able to reproduce the issue even when you're not using YouTube/VSCode, or does it only happen when doing this specifically?

**Comment by Jesewe** [comment]
> Can you also provide a screenshot of **settings > achievement unlocker**?

![image](https://github.com/user-attachments/assets/7148c22b-dc28-4221-8ed4-4a6b43e6df23)

**Comment by Jesewe** [comment]
> Are you able to reproduce the issue even when you're not using YouTube/VSCode, or does it only happen when doing this specifically?

This problem does not always occur, i.e. sometimes everything is normal and sometimes it is not. I will try to record the screen when this problem occurs.

**Comment by Jesewe** [comment]
> I understand, but yeah as mentioned, Windows likely does stuff in the background to limit certain processes and Windows APIs when the desktop is locked (I assume), which could prevent SGI, Steam, Steamworks SDK or any other dependencies from functioning correctly. This is out of my control and my recommendation is to just not lock the desktop while using SGI.

I realise.

**Comment by probablyraging** [comment]
Using your settings, I ran achievement unlocker for the better part of day while minimized to system tray, and I am still unable to reproduce the issue unfortnutely.

As there are also no errors being logged in SGI I would start to look at other programs or anti virus that might be causing the process to close unexpectedly. Also try the following

- Make sure you have a stable internet connection
  - SGI might throw uncaught errors and close if it is unable to perform some functions that rely on internet
- Try older versions of SGI
  - If you can narrow the issue down to a specific version, I will be able to see what changes were made in that version which might of introduced the issue
- Disable anti virus
- Disable auto sleep/hibernate functions
- Uninstall WebView2 and reinstall the latest version
- Make sure Windows is full up to date
