### ISSUE TITLE
Add Tooltips to buttons in webUI

### ISSUE THREAD

**Issue by Slaurits** [probablyraging/steam-game-idler#4]
### Describe the feature

Most sites have tooltips for icon buttons like this:
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/c35ee2cb-7469-45cc-aa0f-73faf0532bc8)
![image](https://github.com/probablyraging/steam-game-idler/assets/83727223/21994186-6ed3-4d4d-a428-35185d888b7b)

The reason I'm asking for this is that the 10s and 3s could be a bit confusing haha

[tooltips showcase](https://www.w3schools.com/howto/howto_css_tooltip.asp)

### Which branch of SGI?

CLI + WebUI

### Is your feature request related to an issue?

No

**Comment by probablyraging** [comment]
I actually added these to the Tauri/.exe version a couple of weeks ago 8c2e000d8afa62d9e5348da06fcb5bb467b1860f, must have forgot to add them to the WebUI version, will push that update shortly. Thanks again!
