### ISSUE TITLE
Auto restart idling after disconnection

### ISSUE THREAD

**Issue by kast1450** [probablyraging/steam-game-idler#40]
### Describe the feature

Hello, I would like to idle games on my account and still use the account actively. This means logging in on my desktop, pressing "Play" on a game, then acknowledging the prompt that says other instances will be disconnected. This disconnects steam-game-idler and gives an error in the CLI and shows the logged in account as "null". To restart idling it's required to login to the server running the CLI and manually restart the CLI. I would like a feature which would periodically attempt to re-login and restart idling automatically while a stop command hasn't been issued.

### Which branch of SGI?

CLI + WebUI

**Comment by lainedfles** [comment]
I think the project is dead. Good luck.

**Comment by probablyraging** [comment]
Sorry, I likely won't be maintaining the CLI version of SGI all that much, or at all. If you would like to work on this feature yourself, you're welcome to submit a pull request.
