### ISSUE TITLE
Cannot install no matter the build

### ISSUE THREAD

**Issue by mkornela** [probablyraging/steam-game-idler#41]
### Describe the issue

Windows install with .msi fails with codes `2503` and then `2502`.
![image](https://github.com/user-attachments/assets/02aa5b63-c010-4a29-9a7f-65e07623736d)
![image](https://github.com/user-attachments/assets/68cf5ea6-46da-479c-a531-8e00843111de)

Compile it yourself fails with those:
```
Build FAILED.

"D:\idler\steam-game-idler\libs\steam-utility\SteamUtility.csproj" (default target) (1) ->
(CoreCompile target) ->
  FormIdler.cs(22,28): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtilit
y.csproj]
  FormIdler.cs(40,25): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtilit
y.csproj]
  FormIdler.cs(49,58): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtilit
y.csproj]
  Program.cs(64,31): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility.
csproj]
  Program.cs(232,35): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility
.csproj]
  Program.cs(312,35): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility
.csproj]
  Program.cs(389,43): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility
.csproj]
  Program.cs(398,39): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility
.csproj]
  Program.cs(403,35): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility
.csproj]
  Program.cs(421,39): error CS1056: Unexpected character '$' [D:\idler\steam-game-idler\libs\steam-utility\SteamUtility
.csproj]

    0 Warning(s)
    10 Error(s)
```

I tried installing it on Windows drive, on all of my other drivers, still nothing.

### Which branch of SGI?

CLI + WebUI

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [X] I have included screenshots/videos
- [ ] I have included a log.txt file
- [X] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Googling the 2502 and 2503 error codes suggests an issue with file/folder permissions, specifically with the Windows `/temp` folder. Try running the MSI installer as admin, and double check your user account has read/write access to the directories you're accessing.

The error you're getting when trying to build it yourself is likely due to using a older version of MSBuild that doesn't have the string interpolation feature. Try .NET SDK that includes MSBuild 14.0 or higher - I should probably mention this in the prerequisites.

**Comment by mkornela** [comment]
> Googling the 2502 and 2503 error codes suggests an issue with file/folder permissions, specifically with the Windows `/temp` folder. Try running the MSI installer as admin, and double check your user account has read/write access to the directories you're accessing.

I tried installing it both with admin and without admin perms, still doesnt install

**Comment by probablyraging** [comment]
> I tried installing it both with admin and without admin perms, still doesnt install

Unfortunately they are Windows Installer errors, not errors thrown by SGI. All I can really suggest is Google those errors and try whatever people recommend
