### ISSUE TITLE
card farming steam credentials not working

### ISSUE THREAD

**Issue by Crexonus** [probablyraging/steam-game-idler#42]
### Describe the issue

I have put in my credentials many times. I have used cookies extension with and without incognito and used the developer tools to get them with and without incognito and it always says invalid 

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [ ] I have included steps to reproduce the issue
- [ ] I have included screenshots/videos
- [ ] I have included a log.txt file
- [ ] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Have you followed the [steps found here](https://github.com/probablyraging/steam-game-idler/wiki/Settings#steam-credentials) - you need to make sure you're getting the credentials from `https://steamcommunity.com/` and not `https://store.steampowered.com/` as they won't work.

Try deleting the cookies stored for `https://steamcommunity.com/`, then sign out and sign back in to your Steam account in the browser to refresh those credentials and try again, or use a different browser completely.

If it's still not working, check to see if you have any cookies called `steamMachineAuth` or `steamParental `. If you do, you might need to disable Steam Family View and Parental Controls on your account first.

**Comment by Crexonus** [comment]
Hey I have found out the reason why it didn't work I was using store.steampowered instead of steamcommunity that fixed my issue thanks and sorry for wasting your time for something so easy lol.
