### ISSUE TITLE
Set an amount of time for game to idle

### ISSUE THREAD

**Issue by dawson2938** [probablyraging/steam-game-idler#43]
### Describe the feature

Set a timer for how long for games to idle. I am trying to idle certain game to get my playtime to match my playstation account so this would be useful instead of having to manually do it. 

### Which branch of SGI?

Base

### Is your feature request related to an issue?

No

**Comment by zevnda** [comment]
Decided to add this as a feature after all. It is added in `v1.6.0-beta.4` and will be available in the stable release of `v.1.6.0`

   - Hover over a `game card` in the `games list` and click the 3 vertical dots to show the `game card menu`, then click `game settings`
   - **Max idle time (minutes)**: Set the max amount of time (in minutes) this game should be idled for. SGI will stop idling this game when the time limit is reached
     - This only affects games that are idled by `manual idle` or `auto idle`, and does not affect games idled by `card farming` or `achievement unlocker`
   - **Max card drops**: Set the max amount of card drops you want `card farming` to farm before it stops farming that game
     - There are no set times or guarantees on card drop intervals, so even though SGI will try to stay within this limit as best as it can, it may not always be perfect
   - **Max achievement unlocks**: Set the max amount of achievements you want `achievement unlocker` to unlock for you. SGI will stop unlocking achievements for this game and remove it from the `achievement unlocker` list
