### ISSUE TITLE
Card unlocker only on one game

### ISSUE THREAD

**Issue by HellHand87** [probablyraging/steam-game-idler#44]
### Describe the issue

so the card unlocker only is on one game, before that it was on for 32 games now only on one
and that game didn't drop a card for 20 hours straight
-now i have changed password so trades cannot be done, and this is the only thing i have done so far
card unlocker is locked on one game i tried giving it a list but it completes it without a second, i reinstalled and gave it new credential but didn't work

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

### Additional Information

- [X] I have included steps to reproduce the issue
- [ ] I have included screenshots/videos
- [ ] I have included a log.txt file
- [X] I have checked for similar issues before reporting

**Comment by probablyraging** [comment]
Can you share your log.txt file. Go to settings > logs > view in file explore

**Comment by probablyraging** [comment]
> hi so i got why cards didn't unlock... funny enough i found out about it when i used another card farmer 😀 so it would be better to add an notice... YOU CANNOT get cards when the game is privet but i still don't get why when i start the card unlocker it would only be one game... [log.txt](https://github.com/user-attachments/files/18126962/log.txt)

Interesting.. Glad you got it sorted, and I will look in to that.

Let me know if you have any more question.
