### ISSUE TITLE
Card Mining - Gmes added to list not mining

### ISSUE THREAD

**Issue by alienation16** [probablyraging/steam-game-idler#9]
### Describe the issue

When attempting to mine card, some games added to the list will not mine, notably CS2 seems to be affected by this, with no other games in the list idling will begin before immediately throwing a "Completed" message

### Which branch of SGI?

Base

### What version of SGI are you using?

Latest version

**Comment by probablyraging** [comment]
Hey mate,

Free to play games such as Counter-Strike 2 only reward cards for spending real money in game.

You can verify this by by going to your **Steam profile > Badges > find Counter-Strike 2 > Click 'How do I earn..'**. This will also show you how many card drops you have remaining for that specific game.

![image](https://github.com/user-attachments/assets/2e43b74c-0f90-45ea-ad32-179746a845b8)

![image](https://github.com/user-attachments/assets/6f7cdb81-b7c3-4074-a0b3-6f9a00465d83)

**Comment by alienation16** [comment]
Ah thanks mate, my bad, I appreciate the clarification
